My PR for Play travis
Otus-DevOps-2021-08/ScoutBert_infra pull request #1
Opened 2021-09-14 21:45 UTC by ScoutBert

выполнено ДЗ N2

2021-09-15 09:07 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз, оставил комментарий к файлу. ДЗ возвращаю на доработку.

2021-09-15 09:07 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот сюда смотрим внимательно =)

2021-09-15 09:37 UTC, ScoutBert commented
Добрый день! Поправил

2021-09-16 07:55 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь апрув!)

2021-09-17 10:54 UTC, merged