Cloud testapp
Otus-DevOps-2021-08/ScoutBert_infra pull request #3
Opened 2021-09-23 15:23 UTC by ScoutBert

# Выполнено ДЗ №4

testapp_IP = 62.84.116.197
testapp_port = 9292

Создание ВМ с запущенным сервисом  instance.sh параметры user-data.yml

yc compute instance create --name reddit-app-auto --hostname reddit-app2 --cores=2 --memory=4 --core-fraction=20 --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-1604-lts,size=10GB --network-interface subnet-name=default-ru-central1-a,nat-ip-version=ipv4 --metadata serial-port-enable=1 --metadata-from-file user-data=./user-data.yml

2021-09-24 09:26 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз, вам стоит ознакомиться с результатами тестов. Стоит обратить внимание на сообщения которые выделены красным, например некоторые файлы не исполняемые и тд.
ДЗ возвращаю на доработку.

2021-09-24 09:38 UTC, ScoutBert commented
Очень странно, писал об этом в ЛК по ДЗ
-rwxrwxrwx 1 asabitov asabitov 205 Sep 23 16:34 deploy.sh
-rwxrwxrwx 1 asabitov asabitov 476 Sep 23 16:32 install_mongodb.sh
-rwxrwxrwx 1 asabitov asabitov 166 Sep 23 16:32 install_ruby.sh

2021-09-28 15:09 UTC, mrgreyves commented
Склонировал репу
![image](https://user-images.githubusercontent.com/34331259/135114655-89ab0369-7e07-4262-940f-ccc45727d0f9.png)
Права все таки не проставлены

2021-09-29 19:26 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув)
ЗЫ - с монгой порой такое бывает в тестах =)

2021-09-30 06:17 UTC, merged