Ansible 3
Otus-DevOps-2021-08/ScoutBert_infra pull request #9
Opened 2021-11-19 14:14 UTC by ScoutBert

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-11-19 14:48 UTC, ScoutBert commented
Добрый день!
не могу победить 
 ×  Command: `cd ansible && ansible-lint playbooks/site.yml --exclude=roles/jdauphant.nginx` exit_status should eq 0
у меня WSL, грешу на права папки ansible

2021-11-19 14:53 UTC, ScoutBert commented
asabitov@DESKTOP-UG5BG2F:/mnt/c/GIT/ScoutBert_infra$ cd ansible && ansible-lint playbooks/site.yml --exclude=roles/jdauphant.nginx
[WARNING]: Ansible is being run in a world writable directory
(/mnt/c/GIT/ScoutBert_infra/ansible), ignoring it as an ansible.cfg source. For
more information see
https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-
world-writable-dir
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the
controller starting with Ansible 2.12. Current version: 3.6.9 (default, Jan 26
2021, 15:33:00) [GCC 8.4.0]. This feature will be removed from ansible-core in
version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
[WARNING]: Ansible is being run in a world writable directory (/mnt/c/GIT/ScoutBert_infra/ansible), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
[WARNING]: While constructing a mapping from /home/asabitov/.ansible/roles/jdauphant.nginx/tasks/configuration.yml, line 62, column 3, found a duplicate dict key (when). Using last defined value only.
[WARNING]: While constructing a mapping from <unicode string>, line 62, column 3, found a duplicate dict key (when). Using last defined value only.

2021-11-22 06:46 UTC, mrgreyves requested changes
Здравствуйте!)
В тестах в основном ругается на Trailing whitespace
Фактически это пробелы, подкорректировать их не сложно. Поправьте их и попробуйте выполнить тесты снова =)

2021-11-22 12:22 UTC, ScoutBert commented
Добрый день! Помогло, использовал 'find . -type f -print0 | xargs -0 dos2unix'

2021-11-23 13:52 UTC, ScoutBert commented
Добрый день! Тесты вроде прошли ))

2021-11-23 20:03 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто, дз принимаю!=)

2021-11-24 09:33 UTC, merged